---
title: "DV_Final"
author: "Tim McCormack"
date: "4/17/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include = FALSE}
library(tidyverse)
library(ggplot2)
library(plotly)
library(magrittr)
```


```{r}
aisles <- read.csv("aisles.csv")
dep <- read.csv("departments.csv")
order_p <- read.csv("order_products__prior.csv")
orders <- read.csv("orders.csv")
products <- read.csv("products.csv")

```


```{r}
head(order_p,20)

orderSize <- orderSize %>% filter()

orderSize <- order_p %>% group_by(order_id) %>% summarise(count = n()) 
```


```{r}
orderSize <- orderSize 
hist(orderSize$count)

```


```{r}
head(orderSize)

fig <- plot_ly(x = orderSize$count, type = "histogram", histnorm = "probability", marker = list(color = "#00CC96")) %>% layout(xaxis = list(tickformat = "digits", title = "# Of Items"), title = "Distribution of Order Sizes", yaxis = list(title = "Proportion Of Orders"))
fig

```



```{r}
head(products)

productOrders1 <- merge(order_p, products, by = "product_id")

```


```{r}
head(productOrders1)
nrow(productOrders1)

productPopularity <- productOrders1 %>% group_by(product_name) %>% summarise(avgPlacement = mean(add_to_cart_order), avgReOrder = mean(reordered), numOrders = n() )

```


```{r}

pnames <- head(productPopularity %>% arrange(-numOrders),350)
keep_names <- pnames$product_name

```


```{r}
pnames

```

```{r}
unpopularProducts <- productPopularity %>% filter(!product_name %in% keep_names)
sum(unpopularProducts$numOrders)

```


```{r}
hist(productPopularity$numOrders, bins = 100)

#ggplot(data = productPopularity, aes(x = product_name, y = numOrders)) + geom_bar(stat = "identity")
```

```{r}

new <- merge(x=productPopularity,y=products,by="product_name",all=T)
new <- select(new, -1,-2,-3,-5,-6)
new <- merge(x=dep,y=new,by='department_id',all=T)

new<- new %>% 
  group_by(department, department_id) %>% 
  summarise(Total = sum(numOrders, na.rm = TRUE))

new


ggplot(new, aes(x="", y=Total, fill=department)) +
  geom_bar(stat="identity", width=1, color="white") +
  coord_polar("y", start=0) +
  
  theme_void() # remove background, grid, numeric labels

#removing smallest groups
new2 <- new %>%
  filter(department != c('bulk')) %>%
  filter(department != c('other')) %>%
  filter(department != c('missing')) %>%
  filter(department != c('pets')) %>%
  filter(department != c('international')) %>%
  filter(department != c('alcohol')) %>%
  filter(department != c('breakfast')) %>%
  filter(department != c('babies')) %>%
  filter(department != c('personal care'))

ggplot(new2, aes(x="", y=Total, fill=department)) +
  geom_bar(stat="identity", width=1, color="white") +
  coord_polar("y", start=0) +
  
  theme_void()


```

```{r}

new <- merge(x=productPopularity,y=products,by="product_name",all=T)
new <- merge(x=new,y=dep,by="department_id",all=T)

new2 <- new %>%
  filter(department != c('bulk')) %>%
  filter(department != c('other')) %>%
  filter(department != c('missing')) %>%
  filter(department != c('pets')) %>%
  filter(department != c('international')) %>%
  filter(department != c('alcohol')) %>%
  filter(department != c('breakfast')) %>%
  filter(department != c('babies')) %>%
  filter(department != c('personal care'))


new2 %>%
  ggplot(aes(x=department, y=avgReOrder))+
  geom_col()+
  scale_x_discrete(guide = guide_axis(n.dodge=3))

#new

orders %>% 
  ggplot(aes(x=order_hour_of_day)) + 
  geom_histogram(stat="count")


orders %>% 
  ggplot(aes(x=days_since_prior_order)) + 
  geom_histogram(stat="count")

```
















